[tool.poetry]
name = "rbs_assets_library"
version = "0.2.0"
description = "Project description"
authors = ["Bill Finger <ur.narmak@gmail.com>"]

[build-system]
requires = ["poetry-core>=1.0.0", "trimesh"]
build-backend = "poetry.core.masonry.api"
